### ISSUE TITLE
Ticket 002 :  SFD 4.8.2 Message erreur sur le sous menu Ordre> Livraison 

### ISSUE THREAD

**Issue by mehdiboumahrou** [benoitcostewiilog/WiiStock#2]
https://www.screencast.com/t/wbfBwnec

**Comment by JeanVivienSicotWiilog** [comment]
erreur en prod mais pas en dev

**Comment by mehdiboumahrou** [comment]
prioritaire !

**Comment by cecilegazaniolwiilog** [comment]
- pb dans une librairie utilisée par phpmyadmin
- pb de migrations de la base non à jour
