### ISSUE TITLE
Ticket 005 : SFD 4.3.3 Modification d'une ligne de réception

### ISSUE THREAD

**Issue by mehdiboumahrou** [benoitcostewiilog/WiiStock#5]
Entrée : Modification d'un article d'une ligne d'article dans une réception puis clic sur modifier 
Sortie : Après le clic sur modifier on est redirigé vers la page stock>article et non la page de réception détail avec les lignes

https://www.screencast.com/t/60Wk4lzlNab

**Comment by JeanVivienSicotWiilog** [comment]
Maintenant lorsqu'on veux modifier un article on est bien renvoyer à la page parent

**Comment by mehdiboumahrou** [comment]
On ne peut plus accéder à la modification d'une ligne d'article réception : 
https://www.screencast.com/t/M6ix7YpVmriT

et correction edite sur l'URl en modifier : 
![image](https://user-images.githubusercontent.com/47534429/53087283-023b6180-3507-11e9-844d-939ef44d8590.png)
