### ISSUE TITLE
Ticket 007 : SFD 4.3.5  Validation par ligne 

### ISSUE THREAD

**Issue by mehdiboumahrou** [benoitcostewiilog/WiiStock#7]
Entrée : Clic sur + articles d'une ligne de réception en cours puis clic sur Fin réception pour validation 
Sortie : Suite à la fin de réception, les quantités à recevoir ne passe pas en quantité reçu et il n'y a pas de date de et heure de réception sur la ligne sélectionnée 

Fonctionnement attendu : 
Validation par ligne : 
o	Dans la colonne action, la validation d’une ligne permet de passer toutes les quantités « à recevoir » en « reçu »
o	Ajoute la date et heure de réception sur la ligne sélectionnée

**Comment by mehdiboumahrou** [comment]
https://www.screencast.com/t/pblffsy9nw

**Comment by JeanVivienSicotWiilog** [comment]
nouveau champs date de reception gerer automatiquement
