### ISSUE TITLE
Impossible de créer des comptes utilisateur sur la base

### ISSUE THREAD

**Issue by benoitcostewiilog** [benoitcostewiilog/WiiStock#77]
Bonjour,

Impossible de créer de compte utilisateur sur le v.0.0.5.
https://www.screencast.com/t/XDICmC9h653

J'aurai besoin de créer les utilisateurs du CEA Leti et les utilsiateurs GT Logistics.

Merci.

Benoit

**Comment by benoitcostewiilog** [comment]
Merci de créer les comptes en suivant : 

-	Cindy : 
o	login : c.egloff@gt-logistics.fr
o	mdp : N332@@fPs
-	Jérémy : 
o	Login : j.suzet@gt-logistics.fr
o	Mdp : u@@d933EU
-	Patrice : 
o	Login : Patrice.NAL@cea.fr
o	Mdp : i@RB68@5q
-	Chrystelle : 
o	Login : christelle.verne-tournon@cea.fr
o	Mdp : @75W5@yvD

**Comment by JeanVivienSicotWiilog** [comment]
https://cl1-test.follow-gt.fr/register

lien pour créer les comptes 
je crée les 4 comptes demandé

**Comment by JeanVivienSicotWiilog** [comment]
Les comptes sont créés je les ai mis en super-admin
